<a href="https://colab.research.google.com/github/AthuSindhu/DSML/blob/main/EXP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
SumandMax

In [ ]:
#sumandmax
import numpy as np
from timeit import Timer
 
# Creating a large array of size 10**5
array = np.random.randint(1000, size=10**5)
 
def sum_using_forloop():
  sum_array=0
  for element in array:
    sum_array += element
 
def sum_using_builtin_method():
  sum_array = sum(array)
 
def sum_using_numpy():
  sum_array = np.sum(array)
 
time_forloop = Timer(sum_using_forloop).timeit(1)
time_builtin = Timer(sum_using_builtin_method).timeit(1)
time_numpy = Timer(sum_using_numpy).timeit(1)
 
print("Summing elements takes %0.9f units using for loop"%time_forloop)
print("Summing elements takes %0.9f units using builtin method"%time_builtin)
print("Summing elements takes %0.9f units using numpy"%time_numpy)
 
print()
 
def max_using_forloop():
  maximum=array[0]
  for element in array:
    if element > maximum:
      maximum = element
 
def max_using_builtin_method():
  maximum = max(array)
 
def max_using_numpy():
  maximum = np.max(array)
 
time_forloop = Timer(max_using_forloop).timeit(1)
time_builtin = Timer(max_using_builtin_method).timeit(1)
time_numpy = Timer(max_using_numpy).timeit(1)
 
print("Finding maximum element takes %0.9f units using for loop"%time_forloop)
print("Finding maximum element takes %0.9f units using built-in method"%time_builtin)
print("Finding maximum element takes %0.9f units using numpy"%time_numpy)

Summing elements takes 0.045999734 units using for loop
Summing elements takes 0.021983831 units using builtin method
Summing elements takes 0.000182825 units using numpy

Finding maximum element takes 0.023286139 units using for loop
Finding maximum element takes 0.020796376 units using built-in method
Finding maximum element takes 0.000286181 units using numpy


In [ ]:
dotproduct

In [ ]:
import numpy as np
from timeit import Timer
 
# Create 2 vectors of same length
length = 100000
vector1 = np.random.randint(1000, size=length)
vector2 = np.random.randint(1000, size=length)
 
# Finds dot product of vectors using for loop
def dotproduct_forloop():
  dot = 0.0
  for i in range(length):
    dot += vector1[i] * vector2[i]
 
# Finds dot product of vectors using numpy vectorization
def dotproduct_vectorize():
  dot = np.dot(vector1, vector2)
   
 
# Finding execution time using timeit
time_forloop = Timer(dotproduct_forloop).timeit(1)
time_vectorize = Timer(dotproduct_vectorize).timeit(1)
 
print("Finding dot product takes %0.9f units using for loop"%time_forloop)
print("Finding dot product takes %0.9f units using vectorization"%time_vectorize)

Finding dot product takes 0.062666671 units using for loop
Finding dot product takes 0.000299713 units using vectorization


outerproduct

In [ ]:
#outerProduct
import numpy as np
from timeit import Timer
 
# Create 2 vectors of same length
length1 = 1000
length2 = 500
vector1 = np.random.randint(1000, size=length1)
vector2 = np.random.randint(1000, size=length2)
 
# Finds outer product of vectors using for loop
def outerproduct_forloop():
  outer_product = np.zeros((length1, length2), dtype='int')
  for i in range(length1):
    for j in range(length2):
      outer_product[i, j] = vector1[i] * vector2[j]
 
# Finds outer product of vectors using numpy vectorization
def outerproduct_vectorize():
  outer_product = np.outer(vector1, vector2)
   
# Finding execution time using timeit
time_forloop = Timer(outerproduct_forloop).timeit(1)
time_vectorize = Timer(outerproduct_vectorize).timeit(1)
 
print("Finding outer product takes %0.9f units using for loop"%time_forloop)
print("Finding outer product takes %0.9f units using vectorization"%time_vectorize)

Finding outer product takes 0.277720506 units using for loop
Finding outer product takes 0.001791968 units using vectorization


elementwiseproduct


In [ ]:
#ElementwiseProduct
import numpy as np
from timeit import Timer
 
# Create 2 vectors of same length
n = 500
m = 700
matrix1 = np.random.randint(1000, size=(n, m))
matrix2 = np.random.randint(1000, size=(n, m))
 
# Multiply 2 matrices using for loop
def multiplication_forloop():
  product = np.zeros((n, m), dtype='int')
  for i in range(n):
    for j in range(m):
      product[i, j] = matrix1[i, j] * matrix2[i, j]
 
# Multiply 2 matrices using numpy vectorization
def multiplication_vectorize():
  product = matrix1 * matrix2
 
# Finding execution time using timeit
time_forloop = Timer(multiplication_forloop).timeit(1)
time_vectorize = Timer(multiplication_vectorize).timeit(1)
 
print("Element Wise Multiplication takes %0.9f units using for loop"%time_forloop)
print("Element Wise Multiplication takes %0.9f units using vectorization"%time_vectorize)

Element Wise Multiplication takes 0.258580441 units using for loop
Element Wise Multiplication takes 0.001145078 units using vectorization


transformation of python

In [ ]:
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of Matrix:")
matrix= [[int(input()) for i in range(column)] for i in range(rows)]
print("-------Your  Matrix is---------")
for n in matrix:
    print(n)

#result matrix of column*row  dimension

result =[[0 for i in range(rows)] for j in range(column)]

#transpose the matrix
for r in range(rows):
   
   for c in range(column):
       #here we are grabbing the row data of matrix and putting it in the column on the result
       result[c][r] = matrix[r][c]

print("Transpose matrix is: ")
for r in result:
    print(r)

Enter the Number of rows : 2
Enter the Number of Columns: 2
Enter the elements of Matrix:
2
4
6
7
-------Your  Matrix is---------
[2, 4]
[6, 7]
Transpose matrix is: 
[2, 6]
[4, 7]


SVD using python

In [7]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
